version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: finance-tracker
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
    networks:
      - mongo-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance-tracker-api
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/finance-tracker
      - PORT=3002
    networks:
      - mongo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finance-tracker-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3002
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongodb_data: